//! Verifier for the signed release update manifest (outcome #477, item 3.2).
//!
//! This is a byte-for-byte port of `verifyManifest` in
//! `scripts/update-manifest.mjs`, which is the reference. Any accepted or
//! rejected input must get the same outcome from both; the cross-implementation
//! vectors in `test-fixtures/update-manifest/vectors.json` (generated by
//! `pnpm generate:update-manifest-vectors`) pin that.
//!
//! The module is pure: no I/O, no clock, no network. It never executes or
//! downloads anything. The order of checks is load-bearing and mirrors the
//! reference: the signature is verified over the raw bytes BEFORE the manifest
//! is parsed, then the bytes must re-serialize to themselves canonically, then
//! the schema is checked, then the validity window.
//!
//! Canonical JSON (docs/RELEASE.md "Update manifest signing") is what
//! JavaScript's `JSON.parse` followed by a sorted `JSON.stringify` produces, so
//! this module carries a small JSON reader that models JavaScript semantics
//! exactly: strings are UTF-16 code-unit sequences (lone surrogates allowed),
//! numbers are IEEE doubles, a duplicate key keeps its last value, and keys
//! sort by UTF-16 code unit.
//!
//! Two differences are intentional:
//!
//! - **Small-order points.** Signatures are checked with `verify_strict`,
//!   which also refuses a small-order public key or `R`. Whether Node accepts
//!   a degenerate trusted key such as the identity point depends on its
//!   OpenSSL build (Node v24.18.1 accepts it, v24.20.0 refuses it), so there
//!   is no cross-implementation vector for it; `small_order_key_is_refused`
//!   pins the Rust behaviour instead. An honest key and signature never
//!   contain a small-order point, so a real signer is unaffected.
//! - **Nesting depth.** The reader refuses documents nested deeper than
//!   32 levels (a stack bound). A signed, non-canonical document that deep is
//!   `manifest_malformed` here and `manifest_not_canonical` in the reference.
//!   Both refuse it; a valid manifest nests three levels deep.

use base64::Engine as _;
use ed25519_dalek::{Signature, VerifyingKey};
use sha2::{Digest, Sha256};

pub const MANIFEST_SCHEMA: f64 = 1.0;
pub const SIGNATURE_SCHEMA: f64 = 1.0;
pub const KEYS_SCHEMA: f64 = 1.0;
pub const MAX_VALIDITY_SECONDS: i64 = 30 * 24 * 60 * 60;
pub const CLOCK_SKEW_MS: i64 = 300 * 1000;
pub const ARCHITECTURES: [&str; 2] = ["aarch64", "x86_64"];
const MAX_SAFE_INTEGER: f64 = 9_007_199_254_740_991.0;
/// Nesting bound for the JSON reader. Real manifests nest three deep.
const MAX_DEPTH: usize = 32;

/// Every reason verification can fail, named as the reference names them.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Reason {
    KeysMalformed,
    NoTrustedKeys,
    SignatureMalformed,
    UnknownKeyId,
    SignatureInvalid,
    ManifestMalformed,
    ManifestNotCanonical,
    ManifestNotYetValid,
    ManifestExpired,
}

impl Reason {
    pub fn as_str(self) -> &'static str {
        match self {
            Reason::KeysMalformed => "keys_malformed",
            Reason::NoTrustedKeys => "no_trusted_keys",
            Reason::SignatureMalformed => "signature_malformed",
            Reason::UnknownKeyId => "unknown_key_id",
            Reason::SignatureInvalid => "signature_invalid",
            Reason::ManifestMalformed => "manifest_malformed",
            Reason::ManifestNotCanonical => "manifest_not_canonical",
            Reason::ManifestNotYetValid => "manifest_not_yet_valid",
            Reason::ManifestExpired => "manifest_expired",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Slot {
    Current,
    Next,
}

impl Slot {
    pub fn as_str(self) -> &'static str {
        match self {
            Slot::Current => "current",
            Slot::Next => "next",
        }
    }
}

#[derive(Debug, Clone)]
pub struct TrustedKey {
    pub key_id: String,
    key: VerifyingKey,
}

#[derive(Debug, Clone)]
pub struct TrustedKeys {
    pub current: Option<TrustedKey>,
    pub next: Option<TrustedKey>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Artifact {
    pub arch: &'static str,
    pub file: String,
    pub sha256: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Manifest {
    pub version: String,
    pub tag: String,
    pub source_sha: String,
    pub artifacts: Vec<Artifact>,
    pub published_at: String,
    pub expires_at: String,
}

impl Manifest {
    pub fn artifact(&self, arch: &str) -> Option<&Artifact> {
        self.artifacts.iter().find(|artifact| artifact.arch == arch)
    }
}

#[derive(Debug, Clone)]
pub struct Verified {
    pub key_id: String,
    pub slot: Slot,
    pub manifest: Manifest,
}

// ---------------------------------------------------------------------------
// JSON with JavaScript semantics

#[derive(Debug, Clone, PartialEq)]
enum Json {
    Null,
    Bool(bool),
    Number(f64),
    String(Vec<u16>),
    Array(Vec<Json>),
    Object(Vec<(Vec<u16>, Json)>),
}

struct Reader<'a> {
    chars: std::iter::Peekable<std::str::Chars<'a>>,
}

impl Reader<'_> {
    fn whitespace(&mut self) {
        while matches!(self.chars.peek(), Some(' ' | '\t' | '\n' | '\r')) {
            self.chars.next();
        }
    }

    fn expect(&mut self, wanted: char) -> Option<()> {
        (self.chars.next()? == wanted).then_some(())
    }

    fn literal(&mut self, word: &str, value: Json) -> Option<Json> {
        for wanted in word.chars() {
            self.expect(wanted)?;
        }
        Some(value)
    }

    fn value(&mut self, depth: usize) -> Option<Json> {
        if depth > MAX_DEPTH {
            return None;
        }
        self.whitespace();
        match *self.chars.peek()? {
            'n' => self.literal("null", Json::Null),
            't' => self.literal("true", Json::Bool(true)),
            'f' => self.literal("false", Json::Bool(false)),
            '"' => self.string().map(Json::String),
            '[' => {
                self.chars.next();
                let mut items = Vec::new();
                self.whitespace();
                if self.chars.peek() == Some(&']') {
                    self.chars.next();
                    return Some(Json::Array(items));
                }
                loop {
                    items.push(self.value(depth + 1)?);
                    self.whitespace();
                    match self.chars.next()? {
                        ',' => continue,
                        ']' => return Some(Json::Array(items)),
                        _ => return None,
                    }
                }
            }
            '{' => {
                self.chars.next();
                let mut entries: Vec<(Vec<u16>, Json)> = Vec::new();
                self.whitespace();
                if self.chars.peek() == Some(&'}') {
                    self.chars.next();
                    return Some(Json::Object(entries));
                }
                loop {
                    self.whitespace();
                    let key = self.string()?;
                    self.whitespace();
                    self.expect(':')?;
                    let value = self.value(depth + 1)?;
                    // JSON.parse keeps the last value for a repeated key.
                    match entries.iter_mut().find(|(existing, _)| *existing == key) {
                        Some(entry) => entry.1 = value,
                        None => entries.push((key, value)),
                    }
                    self.whitespace();
                    match self.chars.next()? {
                        ',' => continue,
                        '}' => return Some(Json::Object(entries)),
                        _ => return None,
                    }
                }
            }
            '-' | '0'..='9' => self.number(),
            _ => None,
        }
    }

    fn digits(&mut self, text: &mut String) -> usize {
        let mut count = 0;
        while let Some(&digit @ '0'..='9') = self.chars.peek() {
            text.push(digit);
            self.chars.next();
            count += 1;
        }
        count
    }

    fn number(&mut self) -> Option<Json> {
        let mut text = String::new();
        if self.chars.peek() == Some(&'-') {
            text.push('-');
            self.chars.next();
        }
        match self.chars.peek()? {
            '0' => {
                text.push('0');
                self.chars.next();
            }
            '1'..='9' => {
                self.digits(&mut text);
            }
            _ => return None,
        }
        if self.chars.peek() == Some(&'.') {
            text.push('.');
            self.chars.next();
            if self.digits(&mut text) == 0 {
                return None;
            }
        }
        if let Some(&marker @ ('e' | 'E')) = self.chars.peek() {
            text.push(marker);
            self.chars.next();
            if let Some(&sign @ ('+' | '-')) = self.chars.peek() {
                text.push(sign);
                self.chars.next();
            }
            if self.digits(&mut text) == 0 {
                return None;
            }
        }
        // Rust's float parsing is correctly rounded, as is ECMAScript's.
        text.parse::<f64>().ok().map(Json::Number)
    }

    fn hex4(&mut self) -> Option<u16> {
        let mut value = 0u16;
        for _ in 0..4 {
            value = value * 16 + self.chars.next()?.to_digit(16)? as u16;
        }
        Some(value)
    }

    fn string(&mut self) -> Option<Vec<u16>> {
        self.expect('"')?;
        let mut units = Vec::new();
        loop {
            match self.chars.next()? {
                '"' => return Some(units),
                '\\' => units.push(match self.chars.next()? {
                    '"' => 0x22,
                    '\\' => 0x5c,
                    '/' => 0x2f,
                    'b' => 0x08,
                    'f' => 0x0c,
                    'n' => 0x0a,
                    'r' => 0x0d,
                    't' => 0x09,
                    'u' => self.hex4()?,
                    _ => return None,
                }),
                c if (c as u32) < 0x20 => return None,
                c => {
                    let mut buffer = [0u16; 2];
                    units.extend_from_slice(c.encode_utf16(&mut buffer));
                }
            }
        }
    }
}

/// `JSON.parse` over UTF-8 bytes decoded with a fatal decoder that keeps a BOM.
fn parse_json(bytes: &[u8]) -> Option<Json> {
    let text = std::str::from_utf8(bytes).ok()?;
    let mut reader = Reader {
        chars: text.chars().peekable(),
    };
    let value = reader.value(0)?;
    reader.whitespace();
    reader.chars.next().is_none().then_some(value)
}

fn hex_digit(value: u16) -> u16 {
    b"0123456789abcdef"[value as usize & 0xf] as u16
}

/// `JSON.stringify` string quoting, appended as UTF-16 code units.
fn quote_into(units: &[u16], out: &mut Vec<u16>) {
    out.push(b'"' as u16);
    let mut index = 0;
    while index < units.len() {
        let unit = units[index];
        let paired_high = (0xd800..0xdc00).contains(&unit)
            && units
                .get(index + 1)
                .is_some_and(|next| (0xdc00..0xe000).contains(next));
        match unit {
            0x22 => out.extend_from_slice(&[0x5c, 0x22]),
            0x5c => out.extend_from_slice(&[0x5c, 0x5c]),
            0x08 => out.extend_from_slice(&[0x5c, b'b' as u16]),
            0x0c => out.extend_from_slice(&[0x5c, b'f' as u16]),
            0x0a => out.extend_from_slice(&[0x5c, b'n' as u16]),
            0x0d => out.extend_from_slice(&[0x5c, b'r' as u16]),
            0x09 => out.extend_from_slice(&[0x5c, b't' as u16]),
            _ if paired_high => {
                out.extend_from_slice(&units[index..index + 2]);
                index += 1;
            }
            _ if unit < 0x20 || (0xd800..0xe000).contains(&unit) => {
                out.extend_from_slice(&[0x5c, b'u' as u16]);
                for shift in [12, 8, 4, 0] {
                    out.push(hex_digit(unit >> shift));
                }
            }
            _ => out.push(unit),
        }
        index += 1;
    }
    out.push(b'"' as u16);
}

/// The reference `canonicalJson`. `None` where the reference throws.
fn canonical_into(value: &Json, out: &mut Vec<u16>) -> Option<()> {
    match value {
        Json::Null => out.extend("null".encode_utf16()),
        Json::Bool(true) => out.extend("true".encode_utf16()),
        Json::Bool(false) => out.extend("false".encode_utf16()),
        Json::Number(number) => {
            let safe = number.fract() == 0.0 && number.abs() <= MAX_SAFE_INTEGER;
            if !safe || (*number == 0.0 && number.is_sign_negative()) {
                return None;
            }
            out.extend(format!("{}", *number as i64).encode_utf16());
        }
        Json::String(units) => quote_into(units, out),
        Json::Array(items) => {
            out.push(b'[' as u16);
            for (index, item) in items.iter().enumerate() {
                if index > 0 {
                    out.push(b',' as u16);
                }
                canonical_into(item, out)?;
            }
            out.push(b']' as u16);
        }
        Json::Object(entries) => {
            let mut sorted: Vec<&(Vec<u16>, Json)> = entries.iter().collect();
            sorted.sort_by(|left, right| left.0.cmp(&right.0));
            out.push(b'{' as u16);
            for (index, (key, item)) in sorted.into_iter().enumerate() {
                if index > 0 {
                    out.push(b',' as u16);
                }
                quote_into(key, out);
                out.push(b':' as u16);
                canonical_into(item, out)?;
            }
            out.push(b'}' as u16);
        }
    }
    Some(())
}

/// The reference `parseCanonical`: `None` when not JSON, else the value and
/// whether `canonicalFileText(value)` reproduces the exact input bytes.
fn parse_canonical(bytes: &[u8]) -> Option<(Json, bool)> {
    let value = parse_json(bytes)?;
    let mut units = Vec::new();
    let canonical = canonical_into(&value, &mut units).is_some() && {
        units.push(b'\n' as u16);
        // Lone surrogates are escaped above, so this conversion cannot fail.
        String::from_utf16(&units).is_ok_and(|text| text.as_bytes() == bytes)
    };
    Some((value, canonical))
}

fn object(value: &Json) -> Option<&[(Vec<u16>, Json)]> {
    match value {
        Json::Object(entries) => Some(entries),
        _ => None,
    }
}

/// The reference `hasExactKeys`: a plain object with exactly these keys.
fn exact_keys<'a>(value: &'a Json, keys: &[&str]) -> Option<&'a [(Vec<u16>, Json)]> {
    let entries = object(value)?;
    let matches = entries.len() == keys.len()
        && keys.iter().all(|key| {
            let wanted: Vec<u16> = key.encode_utf16().collect();
            entries.iter().any(|(existing, _)| *existing == wanted)
        });
    matches.then_some(entries)
}

fn field<'a>(entries: &'a [(Vec<u16>, Json)], key: &str) -> &'a Json {
    let wanted: Vec<u16> = key.encode_utf16().collect();
    entries
        .iter()
        .find(|(existing, _)| *existing == wanted)
        .map(|(_, value)| value)
        .unwrap_or(&Json::Null)
}

/// A string value that is valid Unicode. A lone surrogate cannot match any
/// field pattern in the reference, so treating it as "not a string" agrees.
fn string(value: &Json) -> Option<String> {
    match value {
        Json::String(units) => String::from_utf16(units).ok(),
        _ => None,
    }
}

fn is_lower_hex(value: &str, length: usize) -> bool {
    value.len() == length
        && value
            .bytes()
            .all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f'))
}

fn is_decimal_part(part: &str) -> bool {
    !part.is_empty()
        && part.bytes().all(|b| b.is_ascii_digit())
        && (part == "0" || !part.starts_with('0'))
}

/// `^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$`
pub fn is_stable_version(value: &str) -> bool {
    let parts: Vec<&str> = value.split('.').collect();
    parts.len() == 3 && parts.iter().all(|part| is_decimal_part(part))
}

fn is_base64(value: &str) -> bool {
    let bytes = value.as_bytes();
    if bytes.len() % 4 != 0 {
        return false;
    }
    let padding = bytes.iter().rev().take_while(|&&b| b == b'=').count();
    padding <= 2
        && bytes[..bytes.len() - padding]
            .iter()
            .all(|b| b.is_ascii_alphanumeric() || *b == b'+' || *b == b'/')
}

/// Decodes padded base64 that re-encodes to itself, of exactly `length` bytes.
fn canonical_base64(value: &str, length: usize) -> Option<Vec<u8>> {
    if !is_base64(value) {
        return None;
    }
    let engine = base64::engine::general_purpose::STANDARD;
    let raw = engine.decode(value).ok()?;
    (raw.len() == length && engine.encode(&raw) == value).then_some(raw)
}

fn days_from_civil(year: i64, month: i64, day: i64) -> i64 {
    let year = if month <= 2 { year - 1 } else { year };
    let era = year.div_euclid(400);
    let year_of_era = year - era * 400;
    let month_index = (month + 9) % 12;
    let day_of_year = (153 * month_index + 2) / 5 + day - 1;
    let day_of_era = year_of_era * 365 + year_of_era / 4 - year_of_era / 100 + day_of_year;
    era * 146_097 + day_of_era - 719_468
}

fn days_in_month(year: i64, month: i64) -> i64 {
    match month {
        2 if (year % 4 == 0 && year % 100 != 0) || year % 400 == 0 => 29,
        2 => 28,
        4 | 6 | 9 | 11 => 30,
        _ => 31,
    }
}

/// The reference `parseTimestamp`, in Unix seconds: the
/// `YYYY-MM-DDTHH:MM:SSZ` shape whose `Date.parse` round-trips through
/// `toISOString`, which rules out calendar overflow and `24:00:00`.
pub fn parse_timestamp(value: &str) -> Option<i64> {
    let bytes = value.as_bytes();
    let shape = b"dddd-dd-ddTdd:dd:ddZ";
    if bytes.len() != shape.len()
        || !bytes.iter().zip(shape).all(|(byte, want)| {
            if *want == b'd' {
                byte.is_ascii_digit()
            } else {
                byte == want
            }
        })
    {
        return None;
    }
    let number = |range: std::ops::Range<usize>| value[range].parse::<i64>().ok();
    let (year, month, day) = (number(0..4)?, number(5..7)?, number(8..10)?);
    let (hour, minute, second) = (number(11..13)?, number(14..16)?, number(17..19)?);
    if !(1..=12).contains(&month)
        || !(1..=days_in_month(year, month)).contains(&day)
        || hour > 23
        || minute > 59
        || second > 59
    {
        return None;
    }
    Some(days_from_civil(year, month, day) * 86_400 + hour * 3600 + minute * 60 + second)
}

/// Formats Unix seconds as the manifest's `YYYY-MM-DDTHH:MM:SSZ`.
pub fn format_timestamp(seconds: i64) -> String {
    let days = seconds.div_euclid(86_400);
    let rest = seconds.rem_euclid(86_400);
    // Inverse of days_from_civil (Howard Hinnant's civil_from_days).
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let day_of_era = z - era * 146_097;
    let year_of_era =
        (day_of_era - day_of_era / 1460 + day_of_era / 36_524 - day_of_era / 146_096) / 365;
    let day_of_year = day_of_era - (365 * year_of_era + year_of_era / 4 - year_of_era / 100);
    let month_index = (5 * day_of_year + 2) / 153;
    let day = day_of_year - (153 * month_index + 2) / 5 + 1;
    let month = if month_index < 10 {
        month_index + 3
    } else {
        month_index - 9
    };
    let year = year_of_era + era * 400 + i64::from(month <= 2);
    format!(
        "{year:04}-{month:02}-{day:02}T{:02}:{:02}:{:02}Z",
        rest / 3600,
        rest % 3600 / 60,
        rest % 60
    )
}

fn dmg_file_name(version: &str, arch: &str) -> String {
    format!("Psyche-Build-v{version}-{arch}.dmg")
}

/// The reference `validateManifestShape`, returning the typed manifest.
fn manifest_shape(value: &Json) -> Option<Manifest> {
    let entries = exact_keys(
        value,
        &[
            "artifacts",
            "expires_at",
            "published_at",
            "schema",
            "source_sha",
            "tag",
            "version",
        ],
    )?;
    if *field(entries, "schema") != Json::Number(MANIFEST_SCHEMA) {
        return None;
    }
    let version = string(field(entries, "version")).filter(|v| is_stable_version(v))?;
    let tag = string(field(entries, "tag")).filter(|tag| *tag == format!("v{version}"))?;
    let source_sha = string(field(entries, "source_sha")).filter(|sha| is_lower_hex(sha, 40))?;
    let artifact_entries = exact_keys(field(entries, "artifacts"), &ARCHITECTURES)?;
    let mut artifacts = Vec::new();
    for arch in ARCHITECTURES {
        let artifact = exact_keys(field(artifact_entries, arch), &["file", "sha256"])?;
        let file =
            string(field(artifact, "file")).filter(|f| *f == dmg_file_name(&version, arch))?;
        let sha256 = string(field(artifact, "sha256")).filter(|d| is_lower_hex(d, 64))?;
        artifacts.push(Artifact { arch, file, sha256 });
    }
    let published_at = string(field(entries, "published_at"))?;
    let expires_at = string(field(entries, "expires_at"))?;
    let published = parse_timestamp(&published_at)?;
    let expires = parse_timestamp(&expires_at)?;
    if expires <= published || expires - published > MAX_VALIDITY_SECONDS {
        return None;
    }
    Some(Manifest {
        version,
        tag,
        source_sha,
        artifacts,
        published_at,
        expires_at,
    })
}

/// The reference `keyIdForPublicKey`.
pub fn key_id_for_public_key(raw: &[u8; 32]) -> String {
    Sha256::digest(raw)[..8]
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn key_entry(value: &Json) -> Result<Option<TrustedKey>, Reason> {
    if *value == Json::Null {
        return Ok(None);
    }
    let entries = exact_keys(value, &["keyId", "publicKey"]).ok_or(Reason::KeysMalformed)?;
    let key_id = string(field(entries, "keyId"))
        .filter(|id| is_lower_hex(id, 16))
        .ok_or(Reason::KeysMalformed)?;
    let raw: [u8; 32] = string(field(entries, "publicKey"))
        .and_then(|encoded| canonical_base64(&encoded, 32))
        .and_then(|raw| raw.try_into().ok())
        .ok_or(Reason::KeysMalformed)?;
    if key_id_for_public_key(&raw) != key_id {
        return Err(Reason::KeysMalformed);
    }
    let key = VerifyingKey::from_bytes(&raw).map_err(|_| Reason::KeysMalformed)?;
    Ok(Some(TrustedKey { key_id, key }))
}

/// The reference `parseKeysFile`.
pub fn parse_keys_file(bytes: &[u8]) -> Result<TrustedKeys, Reason> {
    let value = parse_json(bytes).ok_or(Reason::KeysMalformed)?;
    let entries =
        exact_keys(&value, &["current", "next", "schema"]).ok_or(Reason::KeysMalformed)?;
    if *field(entries, "schema") != Json::Number(KEYS_SCHEMA) {
        return Err(Reason::KeysMalformed);
    }
    let current = key_entry(field(entries, "current"))?;
    let next = key_entry(field(entries, "next"))?;
    if current.is_none() && next.is_some() {
        return Err(Reason::KeysMalformed);
    }
    if let (Some(current), Some(next)) = (&current, &next) {
        if current.key_id == next.key_id {
            return Err(Reason::KeysMalformed);
        }
    }
    Ok(TrustedKeys { current, next })
}

/// The reference `parseSignatureEnvelope`.
fn signature_envelope(bytes: &[u8]) -> Option<(String, Signature)> {
    let (value, canonical) = parse_canonical(bytes)?;
    if !canonical {
        return None;
    }
    let entries = exact_keys(&value, &["algorithm", "key_id", "schema", "signature"])?;
    if string(field(entries, "algorithm")).as_deref() != Some("ed25519")
        || *field(entries, "schema") != Json::Number(SIGNATURE_SCHEMA)
    {
        return None;
    }
    let key_id = string(field(entries, "key_id")).filter(|id| is_lower_hex(id, 16))?;
    let raw: [u8; 64] = canonical_base64(&string(field(entries, "signature"))?, 64)?
        .try_into()
        .ok()?;
    Some((key_id, Signature::from_bytes(&raw)))
}

/// The reference `verifyManifest` without `expect`. `now_ms` is Unix time in
/// milliseconds, the unit the reference compares in.
pub fn verify_manifest(
    manifest_bytes: &[u8],
    signature_bytes: &[u8],
    keys: &TrustedKeys,
    now_ms: i64,
) -> Result<Verified, Reason> {
    let trusted: Vec<(Slot, &TrustedKey)> =
        [(Slot::Current, &keys.current), (Slot::Next, &keys.next)]
            .into_iter()
            .filter_map(|(slot, entry)| entry.as_ref().map(|entry| (slot, entry)))
            .collect();
    if trusted.is_empty() {
        return Err(Reason::NoTrustedKeys);
    }
    let (key_id, signature) =
        signature_envelope(signature_bytes).ok_or(Reason::SignatureMalformed)?;
    let (slot, entry) = trusted
        .into_iter()
        .find(|(_, entry)| entry.key_id == key_id)
        .ok_or(Reason::UnknownKeyId)?;
    // verify_strict additionally refuses small-order points. An honest
    // signature never has one, so it accepts exactly what the reference
    // accepts from a real signer while failing closed on contrived inputs.
    entry
        .key
        .verify_strict(manifest_bytes, &signature)
        .map_err(|_| Reason::SignatureInvalid)?;

    let (value, canonical) = parse_canonical(manifest_bytes).ok_or(Reason::ManifestMalformed)?;
    if !canonical {
        return Err(Reason::ManifestNotCanonical);
    }
    let manifest = manifest_shape(&value).ok_or(Reason::ManifestMalformed)?;
    // Both timestamps parsed in manifest_shape.
    let published_ms = parse_timestamp(&manifest.published_at).unwrap_or(i64::MAX) * 1000;
    let expires_ms = parse_timestamp(&manifest.expires_at).unwrap_or(i64::MIN) * 1000;
    if now_ms < published_ms - CLOCK_SKEW_MS {
        return Err(Reason::ManifestNotYetValid);
    }
    if now_ms >= expires_ms {
        return Err(Reason::ManifestExpired);
    }
    Ok(Verified {
        key_id,
        slot,
        manifest,
    })
}

fn compare_decimal(left: &str, right: &str) -> std::cmp::Ordering {
    // Both are canonical decimal strings (no leading zeros), so the longer one
    // is larger and equal lengths compare lexicographically. No overflow.
    left.len().cmp(&right.len()).then_with(|| left.cmp(right))
}

/// Whether stable `candidate` is strictly newer than `running` under semver
/// precedence. `running` may carry a prerelease (`1.2.3-dev`), which sorts
/// before `1.2.3`; build metadata is ignored. `None` when `running` is not a
/// semver version, which callers treat as "not newer".
pub fn is_newer_version(candidate: &str, running: &str) -> Option<bool> {
    if !is_stable_version(candidate) {
        return Some(false);
    }
    let running = running.split('+').next().unwrap_or(running);
    let (core, prerelease) = match running.split_once('-') {
        Some((core, pre)) if !pre.is_empty() => (core, true),
        Some(_) => return None,
        None => (running, false),
    };
    if !is_stable_version(core) {
        return None;
    }
    let order = candidate
        .split('.')
        .zip(core.split('.'))
        .map(|(left, right)| compare_decimal(left, right))
        .find(|order| order.is_ne())
        .unwrap_or(std::cmp::Ordering::Equal);
    Some(order.is_gt() || (order.is_eq() && prerelease))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    const VECTORS: &str = include_str!("../test-fixtures/update-manifest/vectors.json");

    fn vectors() -> Value {
        serde_json::from_str(VECTORS).expect("vectors parse")
    }

    fn keys_from(value: &Value) -> TrustedKeys {
        parse_keys_file(value.to_string().as_bytes()).expect("test keys parse")
    }

    fn decode(value: &Value) -> Vec<u8> {
        base64::engine::general_purpose::STANDARD
            .decode(value.as_str().expect("base64 string"))
            .expect("base64")
    }

    fn now_ms(value: &Value) -> i64 {
        parse_timestamp(value.as_str().unwrap()).unwrap() * 1000
    }

    fn valid_case() -> (Vec<u8>, Vec<u8>, i64) {
        let all = vectors();
        let case = all["cases"]
            .as_array()
            .unwrap()
            .iter()
            .find(|case| case["name"] == "valid_current_key")
            .unwrap()
            .clone();
        (
            decode(&case["manifest_base64"]),
            decode(&case["signature_base64"]),
            now_ms(&case["now"]),
        )
    }

    #[test]
    fn every_reference_vector_gets_the_reference_outcome() {
        let all = vectors();
        let default_keys = keys_from(&all["keys"]);
        let cases = all["cases"].as_array().unwrap();
        assert!(cases.len() >= 44, "vector set shrank");
        let mut divergences = Vec::new();
        for case in cases {
            let name = case["name"].as_str().unwrap();
            let keys = if case["keys"].is_null() {
                default_keys.clone()
            } else {
                keys_from(&case["keys"])
            };
            let result = verify_manifest(
                &decode(&case["manifest_base64"]),
                &decode(&case["signature_base64"]),
                &keys,
                now_ms(&case["now"]),
            );
            // `rust_expect` marks a documented, intentional difference from
            // the reference (see the module docs); everything else must match.
            let expect = if case["rust_expect"].is_null() {
                &case["expect"]
            } else {
                divergences.push(name);
                &case["rust_expect"]
            };
            match result {
                Ok(verified) => {
                    assert_eq!(expect["outcome"], "ok", "{name}: Rust accepted");
                    assert_eq!(expect["slot"], verified.slot.as_str(), "{name}: slot");
                    assert_eq!(expect["key_id"], verified.key_id.as_str(), "{name}: key id");
                    assert_eq!(
                        expect["version"],
                        verified.manifest.version.as_str(),
                        "{name}"
                    );
                }
                Err(reason) => {
                    assert_eq!(expect["outcome"], reason.as_str(), "{name}: Rust rejected")
                }
            }
        }
        assert_eq!(divergences, ["deep_non_canonical_document"]);
    }

    #[test]
    fn small_order_key_is_refused() {
        // The identity point as a trusted key: (R = B, s = 1) satisfies the
        // cofactorless equation for every message. verify_strict refuses it.
        let identity: [u8; 32] = std::array::from_fn(|i| u8::from(i == 0));
        let encoded = base64::engine::general_purpose::STANDARD.encode(identity);
        let keys = serde_json::json!({
            "schema": 1,
            "current": { "keyId": key_id_for_public_key(&identity), "publicKey": encoded },
            "next": null,
        });
        let keys = keys_from(&keys);
        let mut signature = vec![0x58];
        signature.extend([0x66; 31]);
        signature.push(1);
        signature.extend([0; 31]);
        let envelope = format!(
            "{{\"algorithm\":\"ed25519\",\"key_id\":\"{}\",\"schema\":1,\"signature\":\"{}\"}}\n",
            key_id_for_public_key(&identity),
            base64::engine::general_purpose::STANDARD.encode(&signature)
        );
        let (manifest, _, now) = valid_case();
        assert_eq!(
            verify_manifest(&manifest, envelope.as_bytes(), &keys, now).unwrap_err(),
            Reason::SignatureInvalid
        );
    }

    #[test]
    fn rejects_with_wrong_key_set() {
        let all = vectors();
        let (manifest, signature, now) = valid_case();
        // Only the stranger is trusted: the current-key signature is unknown.
        let stranger_only =
            serde_json::json!({ "schema": 1, "current": all["stranger_key"], "next": null });
        assert_eq!(
            verify_manifest(&manifest, &signature, &keys_from(&stranger_only), now).unwrap_err(),
            Reason::UnknownKeyId
        );
        let none = TrustedKeys {
            current: None,
            next: None,
        };
        assert_eq!(
            verify_manifest(&manifest, &signature, &none, now).unwrap_err(),
            Reason::NoTrustedKeys
        );
    }

    #[test]
    fn every_single_byte_flip_is_refused() {
        let all = vectors();
        let keys = keys_from(&all["keys"]);
        let (manifest, signature, now) = valid_case();
        for index in 0..manifest.len() {
            let mut tampered = manifest.clone();
            tampered[index] ^= 0x20;
            assert!(
                verify_manifest(&tampered, &signature, &keys, now).is_err(),
                "byte {index}"
            );
        }
        for index in 0..signature.len() {
            let mut tampered = signature.clone();
            tampered[index] ^= 0x01;
            assert!(
                verify_manifest(&manifest, &tampered, &keys, now).is_err(),
                "sig byte {index}"
            );
        }
    }

    #[test]
    fn keys_file_rules_match_the_reference() {
        let all = vectors();
        let current = all["keys"]["current"].clone();
        let next = all["keys"]["next"].clone();
        let parse = |value: Value| parse_keys_file(value.to_string().as_bytes());
        assert!(parse(serde_json::json!({"schema":1,"current":null,"next":null})).is_ok());
        assert!(parse(serde_json::json!({"schema":1,"current":current,"next":null})).is_ok());
        for bad in [
            serde_json::json!({"schema":1,"current":null,"next":next}),
            serde_json::json!({"schema":1,"current":current,"next":current}),
            serde_json::json!({"schema":2,"current":null,"next":null}),
            serde_json::json!({"schema":1,"current":null}),
            serde_json::json!({"schema":1,"current":{"keyId":"0000000000000000","publicKey":current["publicKey"]},"next":null}),
        ] {
            assert_eq!(parse(bad).unwrap_err(), Reason::KeysMalformed);
        }
        assert_eq!(
            parse_keys_file(b"not json").unwrap_err(),
            Reason::KeysMalformed
        );
    }

    #[test]
    fn canonical_serialization_matches_json_stringify() {
        let canonical = |text: &str| parse_canonical(text.as_bytes()).map(|(_, ok)| ok);
        assert_eq!(canonical(concat!(r#"{"a":"\/"}"#, "\n")), Some(false));
        assert_eq!(
            canonical(concat!(r#"{"a":"\u001f\b\"\\/"}"#, "\n")),
            Some(true)
        );
        assert_eq!(canonical(concat!(r#"{"a":"\u001F"}"#, "\n")), Some(false));
        assert_eq!(canonical("{\"a\":\"\\ud83d\\ude00\"}\n"), Some(false));
        assert_eq!(canonical("{\"a\":\"\u{1f600}\"}\n"), Some(true));
        assert_eq!(canonical("{\"a\":\"\\udc00\"}\n"), Some(true));
        assert_eq!(canonical("{\"a\":\"\u{2028}\"}\n"), Some(true));
        assert_eq!(canonical("[1,-2,9007199254740991]\n"), Some(true));
        assert_eq!(canonical("[9007199254740992]\n"), Some(false));
        assert_eq!(canonical("{\"b\":1,\"a\":2}\n"), Some(false));
        assert_eq!(canonical("[01]\n"), None);
        assert_eq!(canonical("{\"a\":1,}\n"), None);
        assert_eq!(canonical("\"\t\"\n"), None);
        let deep = format!("{}{}\n", "[".repeat(40), "]".repeat(40));
        assert_eq!(canonical(&deep), None);
    }

    #[test]
    fn timestamps_round_trip_like_to_iso_string() {
        for text in [
            "1970-01-01T00:00:00Z",
            "2024-02-29T23:59:59Z",
            "0000-03-01T00:00:00Z",
            "9999-12-31T23:59:59Z",
        ] {
            assert_eq!(format_timestamp(parse_timestamp(text).unwrap()), text);
        }
        assert_eq!(parse_timestamp("1970-01-01T00:00:00Z"), Some(0));
        for bad in [
            "2023-02-29T00:00:00Z",
            "2026-13-01T00:00:00Z",
            "2026-01-01T00:00:60Z",
            "2026-01-01 00:00:00Z",
            "2026-01-01T00:00:00.000Z",
        ] {
            assert_eq!(parse_timestamp(bad), None, "{bad}");
        }
    }

    #[test]
    fn version_precedence_is_semver_and_stable_only() {
        assert_eq!(is_newer_version("0.0.3", "0.0.2"), Some(true));
        assert_eq!(is_newer_version("0.0.2", "0.0.2"), Some(false));
        assert_eq!(is_newer_version("0.0.1", "0.0.2"), Some(false));
        assert_eq!(is_newer_version("0.10.0", "0.9.9"), Some(true));
        assert_eq!(is_newer_version("1.0.0", "0.99.99"), Some(true));
        assert_eq!(is_newer_version("0.0.2", "0.0.2-dev"), Some(true));
        assert_eq!(is_newer_version("0.0.2", "0.0.2+build.5"), Some(false));
        assert_eq!(
            is_newer_version("100000000000000000000.0.0", "1.0.0"),
            Some(true)
        );
        assert_eq!(is_newer_version("0.0.3-rc.1", "0.0.2"), Some(false));
        assert_eq!(is_newer_version("0.0.3", "garbage"), None);
    }

    #[test]
    fn embedded_release_keys_file_parses() {
        let text = include_bytes!("../../../../../release/update-manifest-keys.json");
        assert!(parse_keys_file(text).is_ok());
    }
}
