import fs from 'fs/promises';
import path from 'path';

export const PSYCHE_TMUX_CONFIG_START = '# >>> psyche';
export const PSYCHE_TMUX_CONFIG_END = '# <<< psyche';
export const PSYCHE_TMUX_CONFIG_VERSION = 1;

export type TmuxPresetTheme = 'dark' | 'light';
export type ManagedTmuxConfigAction = 'created' | 'inserted' | 'updated' | 'unchanged';

export interface ManagedTmuxConfigWriteResult {
  configPath: string;
  backupPath?: string;
  action: ManagedTmuxConfigAction;
  changed: boolean;
  managedBlockVersion: number;
}

export function buildRecommendedTmuxConfig(theme: TmuxPresetTheme): string {
  const palette = theme === 'dark'
    ? {
      windowStyle: "set -g window-style 'fg=default,bg=default'",
      activeWindowStyle: "set -g window-active-style 'fg=default,bg=default'",
      paneBorderStyle: 'set -g pane-border-style "fg=colour238 bg=default"',
      activePaneBorderStyle: 'set -g pane-active-border-style "fg=colour141 bg=default"',
      statusStyle: "set -g status-style 'fg=colour183,bg=colour236'",
    }
    : {
      windowStyle: "set -g window-style 'fg=default,bg=default'",
      activeWindowStyle: "set -g window-active-style 'fg=default,bg=default'",
      paneBorderStyle: 'set -g pane-border-style "fg=colour250 bg=default"',
      activePaneBorderStyle: 'set -g pane-active-border-style "fg=colour99 bg=default"',
      statusStyle: "set -g status-style 'fg=colour99,bg=colour254'",
    };

  return [
    '# =============================================',
    '# psyche recommended tmux config',
    `# Theme: ${theme}`,
    '# Generated by psyche onboarding',
    '# =============================================',
    '',
    '# Better support for Ctrl+Shift arrow bindings on newer tmux versions',
    'set -gq extended-keys on',
    '',
    '# Pane visuals',
    "set -g pane-border-format ' #[bold]#P #[default]#{?pane_title,#{pane_title},#{pane_current_command}} '",
    'set -g pane-border-status top',
    palette.windowStyle,
    palette.activeWindowStyle,
    palette.paneBorderStyle,
    palette.activePaneBorderStyle,
    '',
    '# Status bar',
    palette.statusStyle,
    '',
    '# Fast pane navigation',
    'bind -n C-S-Left select-pane -L',
    'bind -n C-S-Right select-pane -R',
    'bind -n C-S-Up select-pane -U',
    'bind -n C-S-Down select-pane -D',
    '',
    '# Mouse + clipboard quality-of-life',
    'set -g mouse on',
    'set -g set-clipboard on',
    'set -gq allow-passthrough all',
    '',
    '# Copy selected text to system clipboard (best effort by platform)',
    `if-shell "command -v pbcopy >/dev/null 2>&1" "bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'"`,
    `if-shell "command -v pbcopy >/dev/null 2>&1" "bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy'"`,
    `if-shell "command -v wl-copy >/dev/null 2>&1" "bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'"`,
    `if-shell "command -v wl-copy >/dev/null 2>&1" "bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'"`,
    `if-shell "command -v xclip >/dev/null 2>&1" "bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard -in'"`,
    `if-shell "command -v xclip >/dev/null 2>&1" "bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard -in'"`,
    '',
    '# Clipboard and cursor compatibility',
    "set -ga terminal-overrides ',xterm-256color:Ms=\\E]52;c;%p2%s\\007'",
    "set -ga terminal-overrides ',*:Ss=\\E[%p1%d q:Se=\\E[2 q'",
    '',
    '# Preserve terminal program info inside tmux',
    'set -ga update-environment "TERM_PROGRAM"',
    '',
  ].join('\n');
}

export function buildPsycheManagedTmuxConfigBlock(theme: TmuxPresetTheme = 'dark'): string {
  return [
    PSYCHE_TMUX_CONFIG_START,
    '# Managed by psyche. Edit outside this block; psyche may replace this block.',
    `# Version: ${PSYCHE_TMUX_CONFIG_VERSION}`,
    buildRecommendedTmuxConfig(theme).trimEnd(),
    PSYCHE_TMUX_CONFIG_END,
    '',
  ].join('\n');
}

export function hasPsycheManagedTmuxConfigBlock(content: string): boolean {
  return content.includes(PSYCHE_TMUX_CONFIG_START) && content.includes(PSYCHE_TMUX_CONFIG_END);
}

/**
 * Markers written by comux, the name this tool shipped under previously.
 *
 * The block they delimit binds keys to a `comux` binary that no longer
 * exists, so leaving it in ~/.tmux.conf means dead keybindings sitting right
 * next to the live ones. It is removed rather than migrated — the clean break
 * applies here too.
 */
const LEGACY_COMUX_TMUX_CONFIG_START = '# >>> comux';
const LEGACY_COMUX_TMUX_CONFIG_END = '# <<< comux';

export function hasLegacyComuxManagedTmuxConfigBlock(content: string): boolean {
  const startIndex = content.indexOf(LEGACY_COMUX_TMUX_CONFIG_START);
  const endIndex = content.indexOf(LEGACY_COMUX_TMUX_CONFIG_END);
  return startIndex !== -1 && endIndex !== -1 && endIndex > startIndex;
}

export function stripLegacyComuxManagedTmuxConfigBlock(content: string): string {
  const startIndex = content.indexOf(LEGACY_COMUX_TMUX_CONFIG_START);
  const endIndex = content.indexOf(LEGACY_COMUX_TMUX_CONFIG_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) {
    return content;
  }

  const replaceEnd = endIndex + LEGACY_COMUX_TMUX_CONFIG_END.length;
  const before = content.slice(0, startIndex).replace(/\s*$/, '');
  const after = content.slice(replaceEnd).replace(/^\s*/, '');
  // Normalize to exactly one trailing newline. `after` usually already ends
  // with one, so appending unconditionally would leave a blank line and make
  // the result differ from an otherwise-identical config purely by whitespace.
  const joined = [before, after].filter(Boolean).join('\n\n').replace(/\s*$/, '');
  return joined ? `${joined}\n` : '';
}

export function upsertPsycheManagedTmuxConfigBlock(
  rawExistingContent: string,
  nextBlock: string
): { content: string; action: ManagedTmuxConfigAction; changed: boolean } {
  // Evict a pre-rename comux block first so `doctor --fix` never leaves two
  // managed blocks side by side.
  const existingContent = stripLegacyComuxManagedTmuxConfigBlock(rawExistingContent);
  const normalizedBlock = nextBlock.endsWith('\n') ? nextBlock : `${nextBlock}\n`;
  const startIndex = existingContent.indexOf(PSYCHE_TMUX_CONFIG_START);
  const endIndex = existingContent.indexOf(PSYCHE_TMUX_CONFIG_END);

  if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
    const replaceEnd = endIndex + PSYCHE_TMUX_CONFIG_END.length;
    const before = existingContent.slice(0, startIndex).replace(/\s*$/, '');
    const after = existingContent.slice(replaceEnd).replace(/^\s*/, '');
    const nextContent = [
      before,
      normalizedBlock.trimEnd(),
      after,
    ].filter(Boolean).join('\n\n') + '\n';

    return {
      content: nextContent,
      // Compare against the ORIGINAL content, not the stripped copy. If the
      // only change was evicting a legacy comux block, comparing against the
      // stripped copy would report `unchanged`, the file would never be
      // written, and the dead block would survive every `doctor --fix`.
      action: nextContent === rawExistingContent ? 'unchanged' : 'updated',
      changed: nextContent !== rawExistingContent,
    };
  }

  const trimmedExisting = existingContent.trimEnd();
  const nextContent = trimmedExisting
    ? `${trimmedExisting}\n\n${normalizedBlock}`
    : normalizedBlock;

  return {
    content: nextContent,
    action: trimmedExisting ? 'inserted' : 'created',
    changed: nextContent !== rawExistingContent,
  };
}

function buildBackupPath(configPath: string, now: Date): string {
  const timestamp = now.toISOString().replace(/[:.]/g, '-');
  return `${configPath}.psyche-backup-${timestamp}`;
}

export async function writePsycheManagedTmuxConfig(
  homeDir: string,
  theme: TmuxPresetTheme = 'dark',
  now: Date = new Date()
): Promise<ManagedTmuxConfigWriteResult> {
  const configPath = path.join(homeDir, '.tmux.conf');
  const block = buildPsycheManagedTmuxConfigBlock(theme);
  let existingContent = '';
  let fileExists = false;

  try {
    existingContent = await fs.readFile(configPath, 'utf-8');
    fileExists = true;
  } catch (error: any) {
    if (error?.code !== 'ENOENT') {
      throw error;
    }
  }

  const result = upsertPsycheManagedTmuxConfigBlock(existingContent, block);
  let backupPath: string | undefined;

  if (result.changed && fileExists && existingContent.length > 0) {
    backupPath = buildBackupPath(configPath, now);
    await fs.copyFile(configPath, backupPath);
  }

  if (result.changed) {
    await fs.mkdir(path.dirname(configPath), { recursive: true });
    await fs.writeFile(configPath, result.content, 'utf-8');
  }

  return {
    configPath,
    backupPath,
    action: result.action,
    changed: result.changed,
    managedBlockVersion: PSYCHE_TMUX_CONFIG_VERSION,
  };
}
