#[cfg(debug_assertions)]
const APP_COMMANDS: &[&str] = &[
    "pty_start",
    "pty_attach",
    "pane_session_metrics",
    "canonical_project_path",
    "pty_write",
    "pty_resize",
    "pty_ack",
    "pty_set_visibility",
    "pty_stop",
    "pty_current_generation",
    "pty_list",
    "pty_transport_metrics",
    "browser_app_shortcut",
    "browser_report_title",
    "browser_automation_result",
    "browser_navigate",
    "browser_set_bounds",
    "browser_hide",
    "browser_hide_all_except",
    "browser_destroy",
    "browser_destroy_many",
    "browser_current_url",
    "browser_reload",
    "browser_eval",
    "browser_script",
    "browser_snapshot",
    "app_environment",
    "coven_sessions",
    "coven_session_kill",
    "workspace_load",
    "workspace_save",
    "native_session_create",
    "native_session_list",
    "native_session_stop",
    "native_session_capture",
    "agent_skills",
    "fs_list_dir",
    "fs_read_text",
    "fs_write_text",
    "git_status",
    "git_worktrees",
    "git_diff",
    "git_log",
    "workspace_metrics",
    "control_provider_start",
    "control_provider_stop",
    "control_provider_upsert",
    "control_provider_remove",
    "control_provider_complete",
    "control_provider_shutdown",
    "control_operator_submit",
    "control_state",
    "runtime_diagnostics",
    "runtime_process_metrics",
    "diagnostics_spawn_fixture",
    "diagnostics_cycle_window",
];

#[cfg(not(debug_assertions))]
const APP_COMMANDS: &[&str] = &[];

#[cfg(debug_assertions)]
const CAPABILITIES_PATH_PATTERN: &str = "./capabilities/**/*.json";

#[cfg(not(debug_assertions))]
const CAPABILITIES_PATH_PATTERN: &str = "./capabilities/*.json";

#[cfg(not(debug_assertions))]
const RELEASE_PERMISSIONS_PATH_PATTERN: &str = "./permissions/autogenerated/[!d]*.toml";

fn main() {
    println!("cargo:rerun-if-changed=capabilities");
    println!("cargo:rerun-if-changed=permissions/autogenerated");

    #[cfg(debug_assertions)]
    let app_manifest = tauri_build::AppManifest::new().commands(APP_COMMANDS);

    #[cfg(not(debug_assertions))]
    let app_manifest = {
        // Release builds keep the checked-in debug-generated permission files
        // out of the app ACL with the explicit non-diagnostic pattern. Keep
        // command autogeneration disabled here: tauri-build's autogeneration
        // pass scans every existing autogenerated file, including debug-only
        // files left by a prior dev build. The explicit pattern below selects
        // only the release-safe checked-in permissions.
        tauri_build::AppManifest::new()
            .commands(APP_COMMANDS)
            .permissions_path_pattern(RELEASE_PERMISSIONS_PATH_PATTERN)
    };

    let attributes = tauri_build::Attributes::new()
        .capabilities_path_pattern(CAPABILITIES_PATH_PATTERN)
        .app_manifest(app_manifest);
    tauri_build::try_build(attributes).expect("failed to run tauri build script");
}
